LEADER_ENABLE = yes
MOUSEKEY_ENABLE = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
SLEEP_LED_ENABLE = no
API_SYSEX_ENABLE = no
SPACE_CADET_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
RGD_MATRIX_ENABLE = no

LINK_TIME_OPIMIZATION_ENABLE = yes

